// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Echo.proto
// Protobuf Java Version: 4.30.2

package org.apache.seata.integration.brpc.dto;

public final class Echo {
    private Echo() {}

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 30,
                /* patch= */ 2,
                /* suffix= */ "",
                Echo.class.getName());
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface EchoRequestOrBuilder
            extends
            // @@protoc_insertion_point(interface_extends:org.apache.seata.integration.brpc.dto.EchoRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string reqMsg = 1;</code>
         * @return Whether the reqMsg field is set.
         */
        boolean hasReqMsg();
        /**
         * <code>required string reqMsg = 1;</code>
         * @return The reqMsg.
         */
        java.lang.String getReqMsg();
        /**
         * <code>required string reqMsg = 1;</code>
         * @return The bytes for reqMsg.
         */
        com.google.protobuf.ByteString getReqMsgBytes();
    }
    /**
     * Protobuf type {@code org.apache.seata.integration.brpc.dto.EchoRequest}
     */
    public static final class EchoRequest extends com.google.protobuf.GeneratedMessage
            implements
            // @@protoc_insertion_point(message_implements:org.apache.seata.integration.brpc.dto.EchoRequest)
            EchoRequestOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 30,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    EchoRequest.class.getName());
        }
        // Use EchoRequest.newBuilder() to construct.
        private EchoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private EchoRequest() {
            reqMsg_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return org.apache.seata.integration.brpc.dto.Echo
                    .internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return org.apache.seata.integration.brpc.dto.Echo
                    .internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.apache.seata.integration.brpc.dto.Echo.EchoRequest.class,
                            org.apache.seata.integration.brpc.dto.Echo.EchoRequest.Builder.class);
        }

        private int bitField0_;
        public static final int REQMSG_FIELD_NUMBER = 1;

        @SuppressWarnings("serial")
        private volatile java.lang.Object reqMsg_ = "";
        /**
         * <code>required string reqMsg = 1;</code>
         * @return Whether the reqMsg field is set.
         */
        @java.lang.Override
        public boolean hasReqMsg() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string reqMsg = 1;</code>
         * @return The reqMsg.
         */
        @java.lang.Override
        public java.lang.String getReqMsg() {
            java.lang.Object ref = reqMsg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    reqMsg_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string reqMsg = 1;</code>
         * @return The bytes for reqMsg.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getReqMsgBytes() {
            java.lang.Object ref = reqMsg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                reqMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasReqMsg()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, reqMsg_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, reqMsg_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.apache.seata.integration.brpc.dto.Echo.EchoRequest)) {
                return super.equals(obj);
            }
            org.apache.seata.integration.brpc.dto.Echo.EchoRequest other =
                    (org.apache.seata.integration.brpc.dto.Echo.EchoRequest) obj;

            if (hasReqMsg() != other.hasReqMsg()) return false;
            if (hasReqMsg()) {
                if (!getReqMsg().equals(other.getReqMsg())) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasReqMsg()) {
                hash = (37 * hash) + REQMSG_FIELD_NUMBER;
                hash = (53 * hash) + getReqMsg().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(
                java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(
                byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseDelimitedFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(org.apache.seata.integration.brpc.dto.Echo.EchoRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code org.apache.seata.integration.brpc.dto.EchoRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements
                // @@protoc_insertion_point(builder_implements:org.apache.seata.integration.brpc.dto.EchoRequest)
                org.apache.seata.integration.brpc.dto.Echo.EchoRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return org.apache.seata.integration.brpc.dto.Echo
                        .internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return org.apache.seata.integration.brpc.dto.Echo
                        .internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.apache.seata.integration.brpc.dto.Echo.EchoRequest.class,
                                org.apache.seata.integration.brpc.dto.Echo.EchoRequest.Builder.class);
            }

            // Construct using org.apache.seata.integration.brpc.dto.Echo.EchoRequest.newBuilder()
            private Builder() {}

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                reqMsg_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return org.apache.seata.integration.brpc.dto.Echo
                        .internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_descriptor;
            }

            @java.lang.Override
            public org.apache.seata.integration.brpc.dto.Echo.EchoRequest getDefaultInstanceForType() {
                return org.apache.seata.integration.brpc.dto.Echo.EchoRequest.getDefaultInstance();
            }

            @java.lang.Override
            public org.apache.seata.integration.brpc.dto.Echo.EchoRequest build() {
                org.apache.seata.integration.brpc.dto.Echo.EchoRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.apache.seata.integration.brpc.dto.Echo.EchoRequest buildPartial() {
                org.apache.seata.integration.brpc.dto.Echo.EchoRequest result =
                        new org.apache.seata.integration.brpc.dto.Echo.EchoRequest(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(org.apache.seata.integration.brpc.dto.Echo.EchoRequest result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.reqMsg_ = reqMsg_;
                    to_bitField0_ |= 0x00000001;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.apache.seata.integration.brpc.dto.Echo.EchoRequest) {
                    return mergeFrom((org.apache.seata.integration.brpc.dto.Echo.EchoRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.apache.seata.integration.brpc.dto.Echo.EchoRequest other) {
                if (other == org.apache.seata.integration.brpc.dto.Echo.EchoRequest.getDefaultInstance()) return this;
                if (other.hasReqMsg()) {
                    reqMsg_ = other.reqMsg_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasReqMsg()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                reqMsg_ = input.readBytes();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object reqMsg_ = "";
            /**
             * <code>required string reqMsg = 1;</code>
             * @return Whether the reqMsg field is set.
             */
            public boolean hasReqMsg() {
                return ((bitField0_ & 0x00000001) != 0);
            }
            /**
             * <code>required string reqMsg = 1;</code>
             * @return The reqMsg.
             */
            public java.lang.String getReqMsg() {
                java.lang.Object ref = reqMsg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        reqMsg_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string reqMsg = 1;</code>
             * @return The bytes for reqMsg.
             */
            public com.google.protobuf.ByteString getReqMsgBytes() {
                java.lang.Object ref = reqMsg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    reqMsg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string reqMsg = 1;</code>
             * @param value The reqMsg to set.
             * @return This builder for chaining.
             */
            public Builder setReqMsg(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqMsg_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }
            /**
             * <code>required string reqMsg = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearReqMsg() {
                reqMsg_ = getDefaultInstance().getReqMsg();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }
            /**
             * <code>required string reqMsg = 1;</code>
             * @param value The bytes for reqMsg to set.
             * @return This builder for chaining.
             */
            public Builder setReqMsgBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqMsg_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:org.apache.seata.integration.brpc.dto.EchoRequest)
        }

        // @@protoc_insertion_point(class_scope:org.apache.seata.integration.brpc.dto.EchoRequest)
        private static final org.apache.seata.integration.brpc.dto.Echo.EchoRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new org.apache.seata.integration.brpc.dto.Echo.EchoRequest();
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<EchoRequest> PARSER =
                new com.google.protobuf.AbstractParser<EchoRequest>() {
                    @java.lang.Override
                    public EchoRequest parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        Builder builder = newBuilder();
                        try {
                            builder.mergeFrom(input, extensionRegistry);
                        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                            throw e.setUnfinishedMessage(builder.buildPartial());
                        } catch (com.google.protobuf.UninitializedMessageException e) {
                            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                        } catch (java.io.IOException e) {
                            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                                    .setUnfinishedMessage(builder.buildPartial());
                        }
                        return builder.buildPartial();
                    }
                };

        public static com.google.protobuf.Parser<EchoRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<EchoRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.apache.seata.integration.brpc.dto.Echo.EchoRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }
    }

    public interface EchoResponseOrBuilder
            extends
            // @@protoc_insertion_point(interface_extends:org.apache.seata.integration.brpc.dto.EchoResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string xid = 1;</code>
         * @return Whether the xid field is set.
         */
        boolean hasXid();
        /**
         * <code>optional string xid = 1;</code>
         * @return The xid.
         */
        java.lang.String getXid();
        /**
         * <code>optional string xid = 1;</code>
         * @return The bytes for xid.
         */
        com.google.protobuf.ByteString getXidBytes();

        /**
         * <code>optional string branchType = 2;</code>
         * @return Whether the branchType field is set.
         */
        boolean hasBranchType();
        /**
         * <code>optional string branchType = 2;</code>
         * @return The branchType.
         */
        java.lang.String getBranchType();
        /**
         * <code>optional string branchType = 2;</code>
         * @return The bytes for branchType.
         */
        com.google.protobuf.ByteString getBranchTypeBytes();

        /**
         * <code>required string reqMsg = 3;</code>
         * @return Whether the reqMsg field is set.
         */
        boolean hasReqMsg();
        /**
         * <code>required string reqMsg = 3;</code>
         * @return The reqMsg.
         */
        java.lang.String getReqMsg();
        /**
         * <code>required string reqMsg = 3;</code>
         * @return The bytes for reqMsg.
         */
        com.google.protobuf.ByteString getReqMsgBytes();
    }
    /**
     * Protobuf type {@code org.apache.seata.integration.brpc.dto.EchoResponse}
     */
    public static final class EchoResponse extends com.google.protobuf.GeneratedMessage
            implements
            // @@protoc_insertion_point(message_implements:org.apache.seata.integration.brpc.dto.EchoResponse)
            EchoResponseOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 30,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    EchoResponse.class.getName());
        }
        // Use EchoResponse.newBuilder() to construct.
        private EchoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private EchoResponse() {
            xid_ = "";
            branchType_ = "";
            reqMsg_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return org.apache.seata.integration.brpc.dto.Echo
                    .internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return org.apache.seata.integration.brpc.dto.Echo
                    .internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.apache.seata.integration.brpc.dto.Echo.EchoResponse.class,
                            org.apache.seata.integration.brpc.dto.Echo.EchoResponse.Builder.class);
        }

        private int bitField0_;
        public static final int XID_FIELD_NUMBER = 1;

        @SuppressWarnings("serial")
        private volatile java.lang.Object xid_ = "";
        /**
         * <code>optional string xid = 1;</code>
         * @return Whether the xid field is set.
         */
        @java.lang.Override
        public boolean hasXid() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string xid = 1;</code>
         * @return The xid.
         */
        @java.lang.Override
        public java.lang.String getXid() {
            java.lang.Object ref = xid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    xid_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string xid = 1;</code>
         * @return The bytes for xid.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getXidBytes() {
            java.lang.Object ref = xid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                xid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BRANCHTYPE_FIELD_NUMBER = 2;

        @SuppressWarnings("serial")
        private volatile java.lang.Object branchType_ = "";
        /**
         * <code>optional string branchType = 2;</code>
         * @return Whether the branchType field is set.
         */
        @java.lang.Override
        public boolean hasBranchType() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional string branchType = 2;</code>
         * @return The branchType.
         */
        @java.lang.Override
        public java.lang.String getBranchType() {
            java.lang.Object ref = branchType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    branchType_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string branchType = 2;</code>
         * @return The bytes for branchType.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getBranchTypeBytes() {
            java.lang.Object ref = branchType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                branchType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int REQMSG_FIELD_NUMBER = 3;

        @SuppressWarnings("serial")
        private volatile java.lang.Object reqMsg_ = "";
        /**
         * <code>required string reqMsg = 3;</code>
         * @return Whether the reqMsg field is set.
         */
        @java.lang.Override
        public boolean hasReqMsg() {
            return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>required string reqMsg = 3;</code>
         * @return The reqMsg.
         */
        @java.lang.Override
        public java.lang.String getReqMsg() {
            java.lang.Object ref = reqMsg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    reqMsg_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string reqMsg = 3;</code>
         * @return The bytes for reqMsg.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getReqMsgBytes() {
            java.lang.Object ref = reqMsg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                reqMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasReqMsg()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, xid_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, branchType_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, reqMsg_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, xid_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, branchType_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, reqMsg_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.apache.seata.integration.brpc.dto.Echo.EchoResponse)) {
                return super.equals(obj);
            }
            org.apache.seata.integration.brpc.dto.Echo.EchoResponse other =
                    (org.apache.seata.integration.brpc.dto.Echo.EchoResponse) obj;

            if (hasXid() != other.hasXid()) return false;
            if (hasXid()) {
                if (!getXid().equals(other.getXid())) return false;
            }
            if (hasBranchType() != other.hasBranchType()) return false;
            if (hasBranchType()) {
                if (!getBranchType().equals(other.getBranchType())) return false;
            }
            if (hasReqMsg() != other.hasReqMsg()) return false;
            if (hasReqMsg()) {
                if (!getReqMsg().equals(other.getReqMsg())) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasXid()) {
                hash = (37 * hash) + XID_FIELD_NUMBER;
                hash = (53 * hash) + getXid().hashCode();
            }
            if (hasBranchType()) {
                hash = (37 * hash) + BRANCHTYPE_FIELD_NUMBER;
                hash = (53 * hash) + getBranchType().hashCode();
            }
            if (hasReqMsg()) {
                hash = (37 * hash) + REQMSG_FIELD_NUMBER;
                hash = (53 * hash) + getReqMsg().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(
                java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(
                byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseDelimitedFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(org.apache.seata.integration.brpc.dto.Echo.EchoResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code org.apache.seata.integration.brpc.dto.EchoResponse}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements
                // @@protoc_insertion_point(builder_implements:org.apache.seata.integration.brpc.dto.EchoResponse)
                org.apache.seata.integration.brpc.dto.Echo.EchoResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return org.apache.seata.integration.brpc.dto.Echo
                        .internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return org.apache.seata.integration.brpc.dto.Echo
                        .internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.apache.seata.integration.brpc.dto.Echo.EchoResponse.class,
                                org.apache.seata.integration.brpc.dto.Echo.EchoResponse.Builder.class);
            }

            // Construct using org.apache.seata.integration.brpc.dto.Echo.EchoResponse.newBuilder()
            private Builder() {}

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                xid_ = "";
                branchType_ = "";
                reqMsg_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return org.apache.seata.integration.brpc.dto.Echo
                        .internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_descriptor;
            }

            @java.lang.Override
            public org.apache.seata.integration.brpc.dto.Echo.EchoResponse getDefaultInstanceForType() {
                return org.apache.seata.integration.brpc.dto.Echo.EchoResponse.getDefaultInstance();
            }

            @java.lang.Override
            public org.apache.seata.integration.brpc.dto.Echo.EchoResponse build() {
                org.apache.seata.integration.brpc.dto.Echo.EchoResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.apache.seata.integration.brpc.dto.Echo.EchoResponse buildPartial() {
                org.apache.seata.integration.brpc.dto.Echo.EchoResponse result =
                        new org.apache.seata.integration.brpc.dto.Echo.EchoResponse(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(org.apache.seata.integration.brpc.dto.Echo.EchoResponse result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.xid_ = xid_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.branchType_ = branchType_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.reqMsg_ = reqMsg_;
                    to_bitField0_ |= 0x00000004;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.apache.seata.integration.brpc.dto.Echo.EchoResponse) {
                    return mergeFrom((org.apache.seata.integration.brpc.dto.Echo.EchoResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.apache.seata.integration.brpc.dto.Echo.EchoResponse other) {
                if (other == org.apache.seata.integration.brpc.dto.Echo.EchoResponse.getDefaultInstance()) return this;
                if (other.hasXid()) {
                    xid_ = other.xid_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (other.hasBranchType()) {
                    branchType_ = other.branchType_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (other.hasReqMsg()) {
                    reqMsg_ = other.reqMsg_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasReqMsg()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                xid_ = input.readBytes();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                branchType_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                reqMsg_ = input.readBytes();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object xid_ = "";
            /**
             * <code>optional string xid = 1;</code>
             * @return Whether the xid field is set.
             */
            public boolean hasXid() {
                return ((bitField0_ & 0x00000001) != 0);
            }
            /**
             * <code>optional string xid = 1;</code>
             * @return The xid.
             */
            public java.lang.String getXid() {
                java.lang.Object ref = xid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        xid_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string xid = 1;</code>
             * @return The bytes for xid.
             */
            public com.google.protobuf.ByteString getXidBytes() {
                java.lang.Object ref = xid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    xid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string xid = 1;</code>
             * @param value The xid to set.
             * @return This builder for chaining.
             */
            public Builder setXid(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                xid_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }
            /**
             * <code>optional string xid = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearXid() {
                xid_ = getDefaultInstance().getXid();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }
            /**
             * <code>optional string xid = 1;</code>
             * @param value The bytes for xid to set.
             * @return This builder for chaining.
             */
            public Builder setXidBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                xid_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private java.lang.Object branchType_ = "";
            /**
             * <code>optional string branchType = 2;</code>
             * @return Whether the branchType field is set.
             */
            public boolean hasBranchType() {
                return ((bitField0_ & 0x00000002) != 0);
            }
            /**
             * <code>optional string branchType = 2;</code>
             * @return The branchType.
             */
            public java.lang.String getBranchType() {
                java.lang.Object ref = branchType_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        branchType_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string branchType = 2;</code>
             * @return The bytes for branchType.
             */
            public com.google.protobuf.ByteString getBranchTypeBytes() {
                java.lang.Object ref = branchType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    branchType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string branchType = 2;</code>
             * @param value The branchType to set.
             * @return This builder for chaining.
             */
            public Builder setBranchType(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                branchType_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }
            /**
             * <code>optional string branchType = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearBranchType() {
                branchType_ = getDefaultInstance().getBranchType();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }
            /**
             * <code>optional string branchType = 2;</code>
             * @param value The bytes for branchType to set.
             * @return This builder for chaining.
             */
            public Builder setBranchTypeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                branchType_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            private java.lang.Object reqMsg_ = "";
            /**
             * <code>required string reqMsg = 3;</code>
             * @return Whether the reqMsg field is set.
             */
            public boolean hasReqMsg() {
                return ((bitField0_ & 0x00000004) != 0);
            }
            /**
             * <code>required string reqMsg = 3;</code>
             * @return The reqMsg.
             */
            public java.lang.String getReqMsg() {
                java.lang.Object ref = reqMsg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        reqMsg_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string reqMsg = 3;</code>
             * @return The bytes for reqMsg.
             */
            public com.google.protobuf.ByteString getReqMsgBytes() {
                java.lang.Object ref = reqMsg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    reqMsg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string reqMsg = 3;</code>
             * @param value The reqMsg to set.
             * @return This builder for chaining.
             */
            public Builder setReqMsg(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqMsg_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }
            /**
             * <code>required string reqMsg = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearReqMsg() {
                reqMsg_ = getDefaultInstance().getReqMsg();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }
            /**
             * <code>required string reqMsg = 3;</code>
             * @param value The bytes for reqMsg to set.
             * @return This builder for chaining.
             */
            public Builder setReqMsgBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqMsg_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:org.apache.seata.integration.brpc.dto.EchoResponse)
        }

        // @@protoc_insertion_point(class_scope:org.apache.seata.integration.brpc.dto.EchoResponse)
        private static final org.apache.seata.integration.brpc.dto.Echo.EchoResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new org.apache.seata.integration.brpc.dto.Echo.EchoResponse();
        }

        public static org.apache.seata.integration.brpc.dto.Echo.EchoResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<EchoResponse> PARSER =
                new com.google.protobuf.AbstractParser<EchoResponse>() {
                    @java.lang.Override
                    public EchoResponse parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        Builder builder = newBuilder();
                        try {
                            builder.mergeFrom(input, extensionRegistry);
                        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                            throw e.setUnfinishedMessage(builder.buildPartial());
                        } catch (com.google.protobuf.UninitializedMessageException e) {
                            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                        } catch (java.io.IOException e) {
                            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                                    .setUnfinishedMessage(builder.buildPartial());
                        }
                        return builder.buildPartial();
                    }
                };

        public static com.google.protobuf.Parser<EchoResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<EchoResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.apache.seata.integration.brpc.dto.Echo.EchoResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\nEcho.proto\022%org.apache.seata.integrati"
                    + "on.brpc.dto\"\035\n\013EchoRequest\022\016\n\006reqMsg\030\001 \002"
                    + "(\t\"?\n\014EchoResponse\022\013\n\003xid\030\001 \001(\t\022\022\n\nbranc"
                    + "hType\030\002 \001(\t\022\016\n\006reqMsg\030\003 \002(\t"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
                descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
        internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_org_apache_seata_integration_brpc_dto_EchoRequest_descriptor,
                        new java.lang.String[] {
                            "ReqMsg",
                        });
        internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_org_apache_seata_integration_brpc_dto_EchoResponse_descriptor,
                        new java.lang.String[] {
                            "Xid", "BranchType", "ReqMsg",
                        });
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
